### ISSUE TITLE
Form submit rules in popup: not closing original

### ISSUE THREAD

**Issue by Achoobert** [digi-serve/kitchensink_app#28]
**Describe the bug**
When I use a _redirect_ submit rule: it does not close the original popup
When the redirected-to popup is closed: the original popup remains open

**To Reproduce**
I commented out all the other tests
https://github.com/digi-serve/kitchensink_app/tree/popupTests

**Expected behavior**
Popups should close in the background when they redirect

**Screenshots**
![image](https://user-images.githubusercontent.com/8057443/169792192-d33fe539-bc4b-4b86-b8d1-4ba84269105e.png)

**Server**
in version 2 kitchen sink tests:

**Comment by nh758** [comment]
I think adding a second submit rule to close the current popup here is best.
