### ISSUE TITLE
Form submit rules: cannot use calculated field

### ISSUE THREAD

**Issue by Achoobert** [digi-serve/kitchensink_app#31]
**Describe the bug**
Cannot use a calculated field for a record rule check: all of them fail and none of the "update record" rules are run

blocker for:
https://github.com/digi-serve/ns_app/issues/12

**To Reproduce**
Run the code in this PR
https://github.com/digi-serve/kitchensink_app/pull/30

![image](https://user-images.githubusercontent.com/8057443/170427189-f45263da-9881-406a-9b33-e03eda4ad864.png)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8057443/170427445-9d71ef50-7613-481c-b5e3-66ae4b357f0f.png)
![image](https://user-images.githubusercontent.com/8057443/170427482-19b7a391-188c-433d-a8be-aa35f3f440bc.png)

## record rules:
![image](https://user-images.githubusercontent.com/8057443/170427768-5a22142e-ac06-4cae-b180-6c8b63d1f3ff.png)

![image](https://user-images.githubusercontent.com/8057443/170427692-0dfebd51-6a4a-49bc-9d3c-319d17488e78.png)

blocker for:
https://github.com/digi-serve/ns_app/issues/12

**Comment by nh758** [comment]
Did this work in v1?

**Comment by Achoobert** [comment]
> Did this work in v1?

Yes, this is how we "balance check" batches in production accounting
```credit``` - ```debit``` has to equal 0
